version: '3.5'

# Services
services:

  # PHP FPM Service
  php:
    container_name: php
    build:
      context: ./docker
    volumes:
      - './:/var/www/html'
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    networks:
      - erp

  # Nginx Service
  nginx:
    container_name: web
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - php
    networks:
      - erp

  # MariaDB Service
  mariadb:
    container_name: db
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: YOURPASSWORDHERE
    volumes:
      - './data:/var/lib/mysql'
    networks:
      - erp

# Volumes
volumes:
  data:

networks:
    erp:
        driver: bridge